# For more info on HTTP files go to https://aka.ms/vs/httpfile

##customers
GET https://localhost:7195/customers

###
POST https://localhost:7195/customers
Content-Type: application/json

{
  "name": "Dave",
  "email": "dave@dave.com",
  "phone": "1234"
}

## movies
## get movies
GET https://localhost:7195/movies
###

## post a movie
POST https://localhost:7195/movies
Content-Type: application/json

{
  "title": "Star Wars",
  "rating": "10",
  "description": "a film about power",
  "runtimeMins": 94,
  "screenings": [
    {
      "screenNumber": 13,
      "capacity": 3000,
      "startsAt": "2023-10-01T08:45:00.000Z"
    }
  ]
}




###

## screenings
## create a screening
POST https://localhost:7195/movies/6/screenings
Content-Type: application/json

{
"screenNumber": 19,
"capacity": 400,
"startsAt": "2023-12-20T14:30:00.00000Z"
}

###
## get all screenings
GET https://localhost:7195/movies/6/screenings